### ISSUE TITLE
OmniDB stops responding

### ISSUE THREAD

**Issue by qris** [OmniDB/OmniDB#783] opened 2018-11-23 13:19 UTC
I have a process inserting rows into a table in a transaction. I try to browse this table (Edit Data) in OmniDB. The whole application locks up and becomes unusable (note the spinners on various panes), with no way to cancel the query:

![image](https://user-images.githubusercontent.com/754175/48945438-3d3af280-ef22-11e8-837d-114997fa0f2b.png)

According to pgAdmin, it is executing queries that are blocked:

![image](https://user-images.githubusercontent.com/754175/48945413-272d3200-ef22-11e8-8b7a-8cee085292b4.png)

**Comment by felipebiox** [comment] 2020-06-02 17:35
Duplicate of #824

**Closed** 2020-06-02 18:09 UTC
Labels: bug
