### ISSUE TITLE
Unstructured layout when starting

### ISSUE THREAD

**Issue by Leonardofreua** [OmniDB/OmniDB#1152] opened 2020-08-13 14:43 UTC
Sometimes when I open OmniDB, the screen is unconfigured, but specifically on the editor side, as shown in the image.

I didn't notice any pattern, sometimes it happens and sometimes it doesn't.

![screenshot](https://user-images.githubusercontent.com/11354911/90148806-283b6e00-dd5a-11ea-8a8e-b4e1dd08039e.png)

**Comment by felipebiox** [comment] 2020-08-13 17:52
Hi @Leonardofreua ,

Is this the browser version? If so, could you tell me which browser/version are you using?

If you may try, does moving the horizontal/vertical resize dashed lines fix the screen?

Best regards

**Comment by Leonardofreua** [comment] 2020-08-13 18:14
No, I installed the OmniDB on my machine. Below the version I'm using:

![image](https://user-images.githubusercontent.com/11354911/90170964-2a5ff580-dd77-11ea-88b6-1c103a5fdf83.png)

**Comment by felipebiox** [comment] 2020-08-13 18:29
I see, still, if you have the time and this happens again, please attempt to use the resizing lines just to see if they fix the screen. Just drag the line a bit and see if all elements fit correctly after dropping the drag.

Since I couldnt reproduce this here, I'm interested in checking if the resize methods still work when you fall into this situation.

All resizing methods have been reworked on v.3 (currently WIP), but I'm still testing for possible scenarios and exceptions.

**Comment by Leonardofreua** [comment] 2020-08-14 16:59
Ok, I will try to do some test when it happens again, it is a rare way to happen, but I will do it as soon as it happens and I open a new Issue with the new information. I will try to update to version 2.17 as well.

Thanks for your attention.

*Looking forward to version 3.x*

**Comment by felipebiox** [comment] 2020-10-28 16:05
Hi @Leonardofreua ,

I noticed you already experimenting with version 3 beta.

This issue shouldn't occur in the new version, we've reworked the rendering and used a new technology for the app build.

I will now close this issue, feel free to open new ones if needed.

Thank you very much for the feedback.

**Closed by felipebiox** 2020-10-28 16:05 UTC
Labels: bug

**Comment by Leonardofreua** [comment] 2020-10-28 17:23
Thank you very much the attention of the whole team.
