### ISSUE TITLE
Is OmniDB not compatibile with MS Internet Explorer v11?

### ISSUE THREAD

**Issue by larryrayleonard** [OmniDB/OmniDB#928] opened 2019-04-19 20:16 UTC

**Comment by pgaro** [comment] 2019-04-29 12:37
obvious duplicate of #929

**Comment by wind39** [comment] 2019-04-30 15:03
Hi @larryrayleonard , and thanks, @pgaro .

Yes, we don't plan to add support to MS Internet Explorer, as its supported is about to be discontinued from Microsoft. We also won't add support for Microsoft Edge, as soon it will be replaced by a Chromium-based version.

Closing this now.

Regards,

William

**Closed by wind39** 2019-04-30 15:03 UTC
