### ISSUE TITLE
resize does not work after "fetch all"

### ISSUE THREAD

**Issue by ccurvey** [OmniDB/OmniDB#995] opened 2019-06-11 12:29 UTC
1. Run a query that would return > 50 results
2. Look at the first 50 results.  Note that you can resize the result columns by dragging the column edges in the title row
3. Click "fetch all" to get the rest of the results
4. Now try to resize the result columns...it no longer works.  (The pointer never changes from the arrow to the drag handle when you mouse over the column edge.)

**Comment by rafaelthca** [comment] 2019-06-11 12:32
Hi @ccurvey,

Yes, this was reported by another user and already fixed. 2.16 is coming out in 2 days with the fix. Thanks for reporting.

Rafael.

**Comment by wind39** [comment] 2019-06-11 12:35
Closing as duplicate of #940 .

**Closed by wind39** 2019-06-11 12:35 UTC
Labels: bug, duplicate
