### ISSUE TITLE
In Firefox, dragging tabs makes them unusable

### ISSUE THREAD

**Issue by andrey-utkin** [OmniDB/OmniDB#871] opened 2019-02-26 19:01 UTC
I'm on master (2.14.0) now, but am observing this since 2.11 which i used before.

Dragging an activity tab (like query, console, edit etc), which reorders them in Chrome, makes tab caption to vanish, and makes it impossible to switch to such a broken tab with a click.

**Comment by andrey-utkin** [comment] 2019-02-26 19:07
This is annoying because drag gesture gets detected sometimes even if you mean just to click on a tab.

**Comment by wind39** [comment] 2019-02-26 19:36
Hi @andrey-utkin ,

Please assess if this is a duplicate of #636 , which is now closed because we didn't manage to simulate.

Regards,
William

**Comment by wind39** [comment] 2019-04-17 20:37
Hi @andrey-utkin ,

We finally managed to fix this, the fix will be included in 2.15 to be released tomorrow.

Best regards,

William

**Comment by wind39** [comment] 2019-04-18 14:26
Hi @andrey-utkin ,

We just released OmniDB 2.15.0 with this fix. Please try and provide your valuable feedback.

Thanks in advance,

William

**Comment by pgaro** [comment] 2019-04-29 15:29
Works at my end.

Regards
pgaro

**Comment by wind39** [comment] 2019-04-30 14:51
Thanks for confirming, @pgaro .

Closing this now.

**Closed by wind39** 2019-04-30 14:51 UTC
Labels: bug, fixed
