### ISSUE TITLE
Implement execute query for selected text in query editor

### ISSUE THREAD

**Issue by palmerj** [OmniDB/OmniDB#373] opened 2018-02-08 18:31 UTC
Like PgAdmin Allows

**Comment by wind39** [comment] 2018-03-03 17:40
Hi @palmerj ,

Thanks for your feedback. We are implementing this feature and will deliver it on next release, 2.6.0, which will be published soon.

We will keep this issue open until there.

Regards,
William

**Comment by wind39** [comment] 2018-03-03 17:41
Duplicate of #396 .

**Comment by wind39** [comment] 2018-03-15 16:00
Hi @palmerj ,

We just released OmniDB 2.6.0 with this implementation. Now you can select a portion of the text in the Query Tab and execute it:

![image](https://user-images.githubusercontent.com/7719686/37474977-5955f8d2-2850-11e8-8d8d-e883b4ecdaf6.png)

The shortcut to execute is the same to execute the entire text or only a portion of it. The default is Ctrl-Q, but version 2.6.0 also allows you to define your own shortcuts:

![image](https://user-images.githubusercontent.com/7719686/37475060-8f218648-2850-11e8-8a41-6a2585b1a5cd.png)

We would like to know your feedback on this, please. So I'm keeping this issue open for now.

Regards,
William Ivanski

**Comment by wind39** [comment] 2018-03-23 19:49
Hi,

It's been a while, so we are closing this issue now. Feel free to comment here or open a new issue anytime!

Thanks and regards,
William Ivanski

**Closed by wind39** 2018-03-23 19:49 UTC
Labels: enhancement
