### ISSUE TITLE
Is there a way to open script from file?

### ISSUE THREAD

**Issue by SachaUA** [OmniDB/OmniDB#701] opened 2018-09-14 05:18 UTC
Is there a way to open a script from a file? 
Thanks.

**Comment by wind39** [comment] 2019-02-20 10:46
Hi @SachaUA ,

Currently this is in our roadmap. We will keep this open to inform you once we have some news.

Regards,

William

**Comment by wind39** [comment] 2019-12-03 17:56
Hi @SachaUA ,

I'm closing this because it is a duplicate of #480 .

Best regards,

William

**Closed** 2020-10-28 18:29 UTC
Labels: duplicate, enhancement
