### ISSUE TITLE
OmniDB server 2.13 error on startup

### ISSUE THREAD

**Issue by hunsakerbn** [OmniDB/OmniDB#808] opened 2018-12-20 16:04 UTC
After upgrading OmniDB server from 2.12 to 2.13 on CentOS 6.5  I get the following error when it tries to start up:

Traceback (most recent call last):
  File "site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
  File "site-packages/django/db/backends/base/base.py", line 194, in connect
  File "site-packages/django/db/backends/sqlite3/base.py", line 159, in get_new_connection
sqlite3.NotSupportedError: URIs not supported

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "omnidb-server.py", line 322, in <module>
  File "site-packages/django/contrib/sessions/backends/db.py", line 109, in clear_expired
  File "site-packages/django/db/models/query.py", line 663, in delete
  File "site-packages/django/db/models/deletion.py", line 272, in delete
  File "site-packages/django/db/transaction.py", line 147, in __enter__
  File "site-packages/django/db/backends/base/base.py", line 378, in get_autocommit
  File "site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
  File "site-packages/django/db/utils.py", line 89, in __exit__
  File "site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
  File "site-packages/django/db/backends/base/base.py", line 194, in connect
  File "site-packages/django/db/backends/sqlite3/base.py", line 159, in get_new_connection
django.db.utils.NotSupportedError: URIs not supported

**Comment by wind39** [comment] 2018-12-20 16:17
Hi @hunsakerbn ,

Thanks for reporting, we are investigating that.

Regards,

William

**Comment by hunsakerbn** [comment] 2019-01-14 19:05
I was able to get things working by replacing the following files in /opt/omnidb-server with versions of those files found elsewhere on my server.
 libsqlite3.so.0
_sqlite3.cpython-36m-x86_64-linux-gnu.so

It appears that one or both of the above files as distributed are of a version not compatible with the version of django that is in the distribution.

**Comment by wind39** [comment] 2019-12-04 21:28
Hi @hunsakerbn ,

I managed to reproduce this:

![image](https://user-images.githubusercontent.com/7719686/70183088-e551d280-16c3-11ea-8854-44ce0c8fee67.png)

Trying to fix.

Regards,

William

**Comment by wind39** [comment] 2019-12-04 22:51
Hi @hunsakerbn ,

I managed to fix this. Now OmniDB server on CentOS 6 starts normally:

![image](https://user-images.githubusercontent.com/7719686/70188200-d7ee1580-16ce-11ea-8e02-4b6148872ebd.png)

![image](https://user-images.githubusercontent.com/7719686/70188316-1d124780-16cf-11ea-82ad-dbb9db4e982a.png)

The issue is that we package OmniDB with Django 2.1.x on Debian and CentOS 7. Django 2.1.x requires SQLite 3.7.x. On CentOS 6, only SQLite 3.6.x works. So for CentOS 6 we need to use Django version 2.0.x instead of 2.1.x.

This issue might explain better: https://code.djangoproject.com/ticket/29624

We are releasing OmniDB 2.17 tomorrow, and I would appreciate if you are able to try this in your CentOS 6 server.

Thanks and best regards,

William

**Comment by wind39** [comment] 2020-12-15 13:46
Closing this now.

**Closed by wind39** 2020-12-15 13:46 UTC
Labels: bug, fixed
