### ISSUE TITLE
Make Databases 2nd Level Container (Under Server)

### ISSUE THREAD

**Issue by jsmith0103** [OmniDB/OmniDB#402] opened 2018-03-07 19:15 UTC
Rather than require a new connection for each database, create a databases container that allows drill down to each database, that then allows drill down into each database (schemas, extensions, etc). Currently I have to select a new connection from the dropdown for each database on the same server. Examples attached, and thank you!

![example1](https://user-images.githubusercontent.com/21117396/37112976-98c13e66-2209-11e8-850e-792381630333.JPG)
![example2](https://user-images.githubusercontent.com/21117396/37112977-98d8894a-2209-11e8-9d26-37806d0a107b.JPG)

**Comment by wind39** [comment] 2018-03-07 20:22
Hi, @jsmith0103 ,

Thanks for your suggestion. It is actually a duplicate of #86, but you provided good details and examples, thank you.

It is in the roadmap, will be implemented soon. We will keep this issue open so you will get notified. Stay tuned!

Regards,
William

**Comment by wind39** [comment] 2018-04-12 15:36
Hi @jsmith0103 ,

We just released 2.7.0 with this feature. Can you please try it? We are keeping this open for a while, any feedback is welcome!

Thanks and regards,
William Ivanski

**Comment by jsmith0103** [comment] 2018-04-12 16:08
LOVE the new look. If possible, I'd rather not have to click "Yes" to "This node belongs to another database, change active database to <DBName>" every time I change databases though. I'd prefer either it default to or give an option to just do it. The "Active Database" tag at the top of the tree should be sufficient, IMHO.

Thank you for getting this implemented!

**Comment by erdusa** [comment] 2018-05-04 14:37
Hi, should not this be closed?

**Closed** 2018-05-04 16:10 UTC
Labels: enhancement
